AllCops:
  Exclude:
    - 'bin/*'
    - 'config/application.rb'
    - 'config/puma.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/spring.rb'
    - 'config/environments/production.rb'
    - 'db/schema.rb'
    - 'config/environments/development.rb'
    - 'db/seeds.rb'
    - 'Gemfile'
    - 'config/environments/test.rb'
    - 'config/initializers/wrap_parameters.rb'
    - 'app/jobs/application_job.rb'
    - 'Rakefile'
    - 'config/initializers/cors.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'config/initializers/apitome.rb'
    - 'config/routes.rb'
    - 'db/migrate/*'
    - 'config/initializers/redis.rb'
    - 'config/deploy.rb'
    - 'db/seeds-more.rb'
Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/GlobalVars:
  AllowedVariables:
    - $redis

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 40
